CONNECT AS: sqlplus / as sysdba
ALTER SESSION: ALTER SESSION SET CONTAINER=OCRL;
DATABASE OPEN: ALTER DATABASE OPEN;

CREATE USER TRAINING identified by 1234;
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
GRANT CONNECT, DBA TO IRTAPP_TRAINING;