CREATE OR REPLACE PACKAGE PKG_EMP AS
    V_SALARY_INC_RATE NUMBER := 0.5;
    CURSOR CUR_EMPS IS SELECT * FROM EMP_BKP;
    PROCEDURE INCREASE_SALARIES;
    FUNCTION GET_AVG_SAL(P_DEPT_ID INT) RETURN NUMBER;
END PKG_EMP;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMP AS
    PROCEDURE INCREASE_SALARIES AS
    BEGIN
        FOR R_EMP IN CUR_EMPS LOOP
            UPDATE EMP_BKP SET SALARY = R_EMP.SALARY+(R_EMP.SALARY*V_SALARY_INC_RATE);
        END LOOP;
    END;
    
    FUNCTION GET_AVG_SAL(P_DEPT_ID INT) RETURN NUMBER AS
    V_AVG_SAL NUMBER :=0;
    BEGIN
        SELECT AVG(SALARY) INTO V_AVG_SAL FROM EMP_BKP WHERE DEPARTMENT_ID=P_DEPT_ID;
        RETURN V_AVG_SAL;
    END;
END PKG_EMP;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(PKG_EMP.GET_AVG_SAL(90));
END;
/

CREATE TABLE LOGS (LOGA_SOURCE VARCHAR2(100), LOG_MESSAGES VARCHAR2(100), LOG_DATE DATE);
/

CREATE OR REPLACE PACKAGE PKG_EMP AS
    V_SALARY_INC_RATE NUMBER := 0.5;
    CURSOR CUR_EMPS IS SELECT * FROM EMP_BKP;
    PROCEDURE INCREASE_SALARIES;
    FUNCTION GET_AVG_SAL(P_DEPT_ID INT) RETURN NUMBER;
END PKG_EMP;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMP AS
    PROCEDURE INCREASE_SALARIES AS
    BEGIN
        FOR R_EMP IN CUR_EMPS LOOP
            UPDATE EMP_BKP SET SALARY = R_EMP.SALARY+(R_EMP.SALARY*V_SALARY_INC_RATE);
        END LOOP;
    END;
    
    FUNCTION GET_AVG_SAL(P_DEPT_ID INT) RETURN NUMBER AS
    V_AVG_SAL NUMBER :=0;
    BEGIN
        INSERT INTO LOGS VALUES('AVG-SAL-LOGSS', 'LOGSS-INSERTED',SYSDATE);
        SELECT AVG(SALARY) INTO V_AVG_SAL FROM EMP_BKP WHERE DEPARTMENT_ID=P_DEPT_ID;
        RETURN V_AVG_SAL;
    END;
END PKG_EMP;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(PKG_EMP.GET_AVG_SAL(90));
END;
/